// Code generated by Arduino IoT Cloud.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "";    // Network SSID (name)
const char PASS[]     = "";    // Network password (use for WPA, or use as key for WEP)


/* all variables uploaded to Cloud should be write here */


void initProperties(){


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
