// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onTempChange();
/* all variables uploaded to Cloud should be write here */
float temp;

void initProperties(){

  ArduinoCloud.addProperty(temp, READWRITE, ON_CHANGE, onTempChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
